# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"\x1a\n\tEchoReply\x12\r\n\x05reply\x18\x01 \x01(\t2}\n\x07Greeter\x12\x35\n\tEchoBidir\x12\x12.greet.EchoRequest\x1a\x10.greet.EchoReply(\x01\x30\x01\x12;\n\x0f\x45\x63hoBidirHangup\x12\x12.greet.EchoRequest\x1a\x10.greet.EchoReply(\x01\x30\x01\x42\x0e\xaa\x02\x0bGrpcServiceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\013GrpcService'
  _ECHOREQUEST._serialized_start=22
  _ECHOREQUEST._serialized_end=52
  _ECHOREPLY._serialized_start=54
  _ECHOREPLY._serialized_end=80
  _GREETER._serialized_start=82
  _GREETER._serialized_end=207
# @@protoc_insertion_point(module_scope)
