# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import greet_pb2 as greet__pb2


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EchoBidir = channel.stream_stream(
                '/greet.Greeter/EchoBidir',
                request_serializer=greet__pb2.EchoRequest.SerializeToString,
                response_deserializer=greet__pb2.EchoReply.FromString,
                )
        self.EchoBidirHangup = channel.stream_stream(
                '/greet.Greeter/EchoBidirHangup',
                request_serializer=greet__pb2.EchoRequest.SerializeToString,
                response_deserializer=greet__pb2.EchoReply.FromString,
                )


class GreeterServicer(object):
    """The greeting service definition.
    """

    def EchoBidir(self, request_iterator, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EchoBidirHangup(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EchoBidir': grpc.stream_stream_rpc_method_handler(
                    servicer.EchoBidir,
                    request_deserializer=greet__pb2.EchoRequest.FromString,
                    response_serializer=greet__pb2.EchoReply.SerializeToString,
            ),
            'EchoBidirHangup': grpc.stream_stream_rpc_method_handler(
                    servicer.EchoBidirHangup,
                    request_deserializer=greet__pb2.EchoRequest.FromString,
                    response_serializer=greet__pb2.EchoReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greet.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def EchoBidir(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/greet.Greeter/EchoBidir',
            greet__pb2.EchoRequest.SerializeToString,
            greet__pb2.EchoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EchoBidirHangup(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/greet.Greeter/EchoBidirHangup',
            greet__pb2.EchoRequest.SerializeToString,
            greet__pb2.EchoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
